# Generated by Django 5.2 on 2026-09-07 12:29

from django.db import migrations, models

USER_REFERENCE_COLUMNS = (
    ("django_admin_log", "user_id"),
    ("inventory_inventorymovement", "performed_by_id"),
    ("purchasing_purchaseorder", "created_by_id"),
    ("purchasing_goodsreceipt", "received_by_id"),
    ("purchasing_purchasereturn", "created_by_id"),
    ("purchasing_supplierpayment", "recorded_by_id"),
    ("sales_sale", "sold_by_id"),
)


def prepare_user_references(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT child.relname, constraint_info.conname, child_column.attname
            FROM pg_constraint constraint_info
            JOIN pg_class child ON child.oid = constraint_info.conrelid
            JOIN pg_attribute child_column
                ON child_column.attrelid = child.oid
                AND child_column.attnum = constraint_info.conkey[1]
            WHERE constraint_info.confrelid = 'accounts_user'::regclass
              AND constraint_info.contype = 'f'
            """
        )
        references = cursor.fetchall()

        for table_name, constraint_name, column_name in references:
            quoted_table = schema_editor.quote_name(table_name)
            quoted_constraint = schema_editor.quote_name(constraint_name)
            quoted_column = schema_editor.quote_name(column_name)
            cursor.execute(
                f"ALTER TABLE {quoted_table} DROP CONSTRAINT {quoted_constraint}"
            )
            cursor.execute(
                f"""
                ALTER TABLE {quoted_table}
                ALTER COLUMN {quoted_column} TYPE varchar(30)
                USING CASE
                    WHEN {quoted_column} IS NULL THEN NULL
                    ELSE 'EMP-' || LPAD({quoted_column}::text, 4, '0')
                END
                """
            )


def restore_user_references(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        for table_name, column_name in USER_REFERENCE_COLUMNS:
            cursor.execute(
                f"ALTER TABLE {schema_editor.quote_name(table_name)} "
                f"ADD FOREIGN KEY ({schema_editor.quote_name(column_name)}) "
                "REFERENCES accounts_user (employee_id) ON DELETE SET NULL"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_employee_id'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('inventory', '0002_warehouse_inventorymovement_warehouse_and_more'),
        ('purchasing', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(prepare_user_references, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.RunPython(restore_user_references, migrations.RunPython.noop),
    ]
