# Generated by Django 5.2.17 on 2026-09-06 05:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('customer_type', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('CLINIC', 'Clinic'), ('HOSPITAL', 'Hospital'), ('PHARMACY', 'Pharmacy'), ('DISTRIBUTOR', 'Distributor'), ('OTHER', 'Other')], default='WALK_IN', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('credit_terms_days', models.PositiveIntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
