# Generated by Django 5.2 on 2026-09-08 03:04

from django.db import migrations, models


def move_sale_customer_references(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            'ALTER TABLE "sales_sale" DROP CONSTRAINT IF EXISTS '
            '"sales_sale_customer_id_2d66a408_fk_customers_customer_id"'
        )
        cursor.execute(
            'ALTER TABLE "sales_sale" ALTER COLUMN "customer_id" '
            'TYPE varchar(40) USING "customer_id"::text'
        )
        cursor.execute(
            'UPDATE "sales_sale" AS sale '
            'SET "customer_id" = customer."code" '
            'FROM "customers_customer" AS customer '
            'WHERE sale."customer_id" = customer."id"::text'
        )


def restore_sale_customer_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            'ALTER TABLE "sales_sale" ADD CONSTRAINT '
            '"sales_sale_customer_id_2d66a408_fk_customers_customer_id" '
            'FOREIGN KEY ("customer_id") REFERENCES "customers_customer" '
            '("code") DEFERRABLE INITIALLY DEFERRED'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            move_sale_customer_references,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.RunPython(
            restore_sale_customer_constraint,
            migrations.RunPython.noop,
        ),
    ]
